sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --output-path dist/prod --base-href  "https://arpi-security.info"
  - LANGUAGE=en ng test --watch false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
  repo: ArPIHomeSecurity/www
  target_branch: gh-pages
  fqdn: arpi-security.info