sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "14"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --configuration production --output-path dist/prod --base-href  "https://www.arpi-security.info"
  - LANGUAGE=en ng test --watch false

deploy:
  provider: pages
  local-dir: dist/prod
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  repo: ArPIHomeSecurity/www
  target_branch: gh-pages
  fqdn: www.arpi-security.info
