name: Deploy the web page

on:
  push:
    branches:
      - main

# Add permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment runs at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-webpage:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies 🔧
        run: |
          npm ci
          npm install -g @angular/cli

      - name: Build application (SSG) 💪
        run: |
          ng build --configuration production --base-href  "https://www.arpi-security.info"

      - name: Test application 🤞
        run: |
          LANGUAGE=en ng test --watch false

      - name: Setup Pages 📄
        uses: actions/configure-pages@v6

      - name: Upload artifact 📦
        uses: actions/upload-pages-artifact@v5
        with:
          path: './dist-prod/browser'

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v5